# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-20 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_auto_20160818_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='rate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
