# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-20 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0007_auto_20160820_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamedetailhitter',
            name='AB',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamedetailhitter',
            name='BB',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamedetailhitter',
            name='CS',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamedetailhitter',
            name='HBP',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamedetailhitter',
            name='RBI',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamedetailhitter',
            name='SB',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamedetailhitter',
            name='hit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamedetailhitter',
            name='run',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamedetailpitcher',
            name='BB',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamedetailpitcher',
            name='HBP',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamedetailpitcher',
            name='HR',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamedetailpitcher',
            name='K',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamedetailpitcher',
            name='hit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamedetailpitcher',
            name='pitches',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamedetailpitcher',
            name='run',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hitterhasleague',
            name='AB',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hitterhasleague',
            name='BB',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hitterhasleague',
            name='CS',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hitterhasleague',
            name='H',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hitterhasleague',
            name='HBP',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hitterhasleague',
            name='HR',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hitterhasleague',
            name='K',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hitterhasleague',
            name='R',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hitterhasleague',
            name='RBI',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hitterhasleague',
            name='SB',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hitterhasleague',
            name='double',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hitterhasleague',
            name='game',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hitterhasleague',
            name='triple',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hitterhasteam',
            name='AB',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hitterhasteam',
            name='BB',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hitterhasteam',
            name='CS',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hitterhasteam',
            name='H',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hitterhasteam',
            name='HBP',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hitterhasteam',
            name='HR',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hitterhasteam',
            name='K',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hitterhasteam',
            name='R',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hitterhasteam',
            name='RBI',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hitterhasteam',
            name='SB',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hitterhasteam',
            name='double',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hitterhasteam',
            name='game',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hitterhasteam',
            name='triple',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pitcherhasleague',
            name='BB',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pitcherhasleague',
            name='HBP',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pitcherhasleague',
            name='HR',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pitcherhasleague',
            name='K',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pitcherhasleague',
            name='game',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pitcherhasleague',
            name='hit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pitcherhasleague',
            name='hold',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pitcherhasleague',
            name='ininig',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pitcherhasleague',
            name='lose',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pitcherhasleague',
            name='pitches',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pitcherhasleague',
            name='run',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pitcherhasleague',
            name='save',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pitcherhasleague',
            name='win',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pitcherhasteam',
            name='BB',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pitcherhasteam',
            name='HBP',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pitcherhasteam',
            name='HR',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pitcherhasteam',
            name='K',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pitcherhasteam',
            name='game',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pitcherhasteam',
            name='hit',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pitcherhasteam',
            name='hold',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pitcherhasteam',
            name='ininig',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pitcherhasteam',
            name='lose',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pitcherhasteam',
            name='run',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pitcherhasteam',
            name='save',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pitcherhasteam',
            name='win',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teamhasleague',
            name='draw',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teamhasleague',
            name='lose',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teamhasleague',
            name='win',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
