# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-20 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0009_auto_20160820_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitcherhasteam',
            name='BB',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pitcherhasteam',
            name='HBP',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pitcherhasteam',
            name='HR',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pitcherhasteam',
            name='K',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pitcherhasteam',
            name='game',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pitcherhasteam',
            name='hit',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pitcherhasteam',
            name='hold',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pitcherhasteam',
            name='ininig',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pitcherhasteam',
            name='lose',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pitcherhasteam',
            name='pitches',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pitcherhasteam',
            name='run',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pitcherhasteam',
            name='save',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pitcherhasteam',
            name='win',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
