# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-20 09:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0010_auto_20160820_1828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pitcherhasteam',
            old_name='save',
            new_name='saves',
        ),
    ]
