# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-20 09:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0011_auto_20160820_1849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamedetailpitcher',
            old_name='save',
            new_name='saves',
        ),
        migrations.RenameField(
            model_name='pitcherhasleague',
            old_name='save',
            new_name='saves',
        ),
    ]
