# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160526173010 on 2016-08-22 09:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0012_auto_20160820_1851'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='player',
            managers=[
                ('objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='league',
            field=models.ManyToManyField(null=True, to='university.League'),
        ),
        migrations.RemoveField(
            model_name='player',
            name='team',
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ManyToManyField(null=True, to='university.Team'),
        ),
    ]
