# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160526173010 on 2016-08-22 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0013_auto_20160822_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='league',
            field=models.ManyToManyField(blank=True, to='university.League'),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ManyToManyField(blank=True, to='university.Team'),
        ),
    ]
