# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-29 06:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0014_auto_20160822_1804'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='player',
            managers=[
            ],
        ),
    ]
