# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-01 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmateurGameDetailHitter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ining_1', models.CharField(blank=True, max_length=100)),
                ('ining_2', models.CharField(blank=True, max_length=100)),
                ('ining_3', models.CharField(blank=True, max_length=100)),
                ('ining_4', models.CharField(blank=True, max_length=100)),
                ('ining_5', models.CharField(blank=True, max_length=100)),
                ('ining_6', models.CharField(blank=True, max_length=100)),
                ('ining_7', models.CharField(blank=True, max_length=100)),
                ('ining_8', models.CharField(blank=True, max_length=100)),
                ('ining_9', models.CharField(blank=True, max_length=100)),
                ('AB', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('hit', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('run', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('RBI', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('SB', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('CS', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('BB', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('HBP', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AmateurGameDetailPitcher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win', models.NullBooleanField()),
                ('saves', models.NullBooleanField()),
                ('hold', models.NullBooleanField()),
                ('HR', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('hit', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('K', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('run', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('BB', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('HBP', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('pitches', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AmateurGamePlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AmateurGameSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_date', models.DateField(blank=True)),
                ('team', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AmateurHitterHasLeague',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AB', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('H', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('double', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('triple', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('HR', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('R', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('RBI', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('BB', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('HBP', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('K', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('SB', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('CS', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('game', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AmateurHitterHasTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AB', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('H', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('double', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('triple', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('HR', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('R', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('RBI', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('BB', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('HBP', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('K', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('SB', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('CS', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('game', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AmateurLeague',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='')),
                ('manager', models.CharField(blank=True, max_length=20)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('finish_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AmateurPitcherHasLeague',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('inings', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('win', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('lose', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('saves', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('hold', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('hit', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('HR', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('run', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('BB', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('HBP', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('K', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('pitches', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amateur.AmateurLeague')),
            ],
        ),
        migrations.CreateModel(
            name='AmateurPitcherHasTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('win', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('lose', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('inings', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('saves', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('hold', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('hit', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('HR', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('run', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('BB', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('HBP', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('K', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('pitches', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AmateurTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('logo', models.ImageField(blank=True, upload_to='')),
                ('manager', models.CharField(blank=True, max_length=20)),
                ('rate', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AmateurTeamHasLeague',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('win', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('lose', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('draw', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amateur.AmateurLeague')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amateur.AmateurTeam')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='amateurteam',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amateur.Region'),
        ),
        migrations.AddField(
            model_name='amateurpitcherhasteam',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amateur.AmateurTeam'),
        ),
        migrations.AddField(
            model_name='amateurhitterhasteam',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amateur.AmateurTeam'),
        ),
        migrations.AddField(
            model_name='amateurhitterhasleague',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amateur.AmateurLeague'),
        ),
        migrations.AddField(
            model_name='amateurgameschedule',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amateur.AmateurLeague'),
        ),
        migrations.AddField(
            model_name='amateurgameschedule',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amateur.AmateurGamePlace'),
        ),
        migrations.AddField(
            model_name='amateurgamedetailpitcher',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amateur.AmateurGameSchedule'),
        ),
        migrations.AddField(
            model_name='amateurgamedetailhitter',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amateur.AmateurGameSchedule'),
        ),
    ]
