# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-03 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amateur', '0002_auto_20160901_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amateurleague',
            name='logo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
