# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-03 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amateur', '0003_auto_20160903_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amateurgameschedule',
            name='game_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
